In [2]:
import numpy as np

In [19]:
arr=np.array([[3,6,32,7]])

In [20]:
arr[0, 1]

6

In [21]:
arr[0,1]

6

In [25]:
arr.shape

(1, 4)

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr[0,1]=45


In [28]:
arr

array([[ 3, 45, 32,  7]])

In [29]:
listarr=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
listarr.shape

(3, 3)

In [31]:
listarr.size

9

In [32]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace=np.linspace(1,5,12)

In [35]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [38]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.shape

(99,)

In [3]:
emp=np.empty((4,6))

In [5]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
x=[[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [7]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [8]:
ar.sum(axis=0)

array([12,  8,  9])

In [9]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [10]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [11]:
ar.flat

In [13]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [14]:
ar.ndim

2

In [15]:
ar.nbytes

72

In [16]:
ar.size

9

In [17]:
ar.max()

7

In [18]:
ar.min()

0

In [27]:
one=np.array([1,3,0,4,634,2])

In [28]:
one.argmax() ##gives the index where max is element is present

4

In [30]:
one.argmin() ##gives the index where min is element is present

2

In [32]:
one.argsort()   ## it will give those index in order where its respective sorted elements should be there 

array([2, 0, 5, 1, 3, 4])

In [33]:
ar.argmax(axis=0)

array([2, 1, 1])

In [34]:
ar.argmax(axis=1)

array([2, 2, 0])

In [35]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [36]:
np.where(ar>5)  ## returns the array of tuples in which the indexes are there for this condition

(array([1, 2]), array([2, 0]))

In [39]:
type(np.where(ar>5))

tuple

In [40]:
np.count_nonzero(ar)

8